name: fire_chat
description: "Chat application with Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  #iOS
  cupertino_icons: ^1.0.8

  #firebase
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1

  #navigation
  go_router: ^17.0.1

  #state management
  flutter_bloc: ^9.1.1

  #other
  equatable: ^2.0.7
  uuid: ^4.5.2

  #local storage
  shared_preferences: ^2.5.4

  #ui



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

